### ISSUE TITLE
Cannot save video

### ISSUE THREAD

**Issue by Momeks** [lhuanyu/ARScreenRecorder#1]
I am using ARScreenRecorder.swift to record ARKit scene. The problem is when I stop recording,the video file won't save in camera roll ,and I am getting this error :

`Error Domain=NSCocoaErrorDomain Code=-1 "(null)"`

how to fix this ?

**Comment by lhuanyu** [comment]
Do you just use the **ARScreenRecorder.swift** rather than the whole project?  It is probably you don't have the permission of  the photo library additions. 

You need add the **Privacy Description of Photo Library Additions Usage** in your **info.plist**.

**Comment by Momeks** [comment]
Yes, I added all permissions :
![screen shot 2018-06-20 at 7 12 23 pm](https://user-images.githubusercontent.com/113414/41665759-fc311564-74bd-11e8-9aea-787ce6e7616f.jpg)

but no success !

**Comment by Momeks** [comment]
Did you test it on your device ?

**Comment by lhuanyu** [comment]
Yes, I have tested in my iPhone 6s plus last year. [Click to view my demo video.](https://luohuanyu.com/resources/two_cups.mp4)

Maybe there are something wrong in the new iOS? This repository has no update since last year.
